# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74566bfa8d605bff8c6bd3e82642c1a64ef54e0c5532d6cc26dc54693c0290fd03ce11fb31123922b388d0787ffdde6522eed246dc33a6a53e1579aa02ab2242

test:
  secret_key_base: 31831ed7498eb0c18aee15cc130cd2440d9c90215e35db7a463113ebae925796e958ac9fd2a08ecda485949475d0c7424872771082f017f377637ae5a8007770

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
